flamedisx/core.py
flamedisx/x1t_sr0.py
notebooks/flamedisx_tf2.ipynb

Rewrite flamedisx to use tensorflow 2.0.0-beta0 and tensorflow_probability
Replaced many numpy functions with their tensorflow counterparts
Focussing on fast likelihood computation.
Runs on colab GPU nodes via flamedisx_tf2.ipynb notebook

Port flamedisx to tensorflow

---

.travis.yml
flamedisx/core.py
flamedisx/x1t_sr0.py
flamedisx/xenon_corrections.py
notebooks/flamedisx_tf2.ipynb
requirements.txt
tests/test_core.py

This:
* "Ports the flamedisx tests to tensorflow"... which in practice means adding '.numpy()' after the flamedisx calls, so we can then use numpy for the tests.
* Removes the depedency on straxen by duplicating the necessary pieces of code. When straxen moves away from tensorflow 1, we can change this (but that could be a while).
* Fix a few bugs that made the tests fail, but did not cause a visible problem in the GPU tests in colab:
* lookup_axis1 used out-of-bounds indices
* Added a few numpy_out and .values to prevent pandas Series from messing up simulate_nq. On master this code currently causes a core dump.
* The bound of {quantum}_produced was calculated so weirdly that it could come out lower than the MLE. This was likely present already before the tensorflow port, but it …

Fix tests and setup for CPU development

---

flamedisx/__init__.py
flamedisx/core.py
flamedisx/utils.py
flamedisx/x1t_sr0.py
flamedisx/xenon_corrections.py
notebooks/flamedisx_tf2.ipynb
notebooks/models_check.ipynb
requirements.txt
tests/test_core.py

This adds the following:
* Port the remaining functions in ``x1t_sr0.py``, and the core function ``_dimsize``, to tensorflow. All functions called in ``likelihood`` should now be pure tensorflow.
* The S1 and S2 relative light yields are now evaluated once during set_data, rather than every time during a likelihood call. This is done by the new function ``add_extra_columns``.
* ``likelihood`` is now a ``@tf.function`` function that returns tensors. It does not use batching and only takes the likelihood parameters as arguments. It seems to work as expected (first call is slow, next ones faster), though I've only been able to test this with a few events on my laptop.
* Move the crude batching to a new function ``batched_likelihood``, which returns numpy arrays. This evaluates likelihoods …

Port remaining functions to tf, rearrange things

---

flamedisx/inference.py
flamedisx/source.py
requirements.txt

I've rewritten the `inverse_hessian` method, it is now cleaner and faster.
Instead of calculating the matrix element by element it is now computed row by row using only Tensorflow functions and one list comprehension. All Numpy code is removed, batching is preserved.
Even though this implementation computes the entire Hessian matrix and does not exploit the fact the matrix is symmetric it is still about 5x to 8x faster than the previous implementation. Running the test_ll notebook on Colab I see the time for one function call go down from 55s to around 8s on a Colab GPU node).
I've tried running the function with Autograph but this results in an error. Although that may also be related to `minus_ll()` which does not run with Autograph either.
If `.hessians` is added to `GradientTape` is a …

Improving Hessian computation

---

flamedisx/utils.py

This optimizes the `lookup_axis1` function and speeds up `differential_rate` by almost a factor 2 for NR data.
When profiling the `differential_rate` function we see that in `lookup_axis1` memory is copied back to the host while the GPU remains idle. The `tf.clip_by_value`, addition and `tf.reshape` is done on the CPU instead of the GPU, this is because the tensor is cast to an integer type (since we later give to `tf.gather`).
By putting the cast after the clip and reshape operations everything is executed on the GPU instead.
Running `differential_rate` on Colab with 1/8 of the NR data and `batch_size=40` the time decreases from 265ms to 140ms.
Also on ER data the differential rate is calculated slightly faster (1.27s from 1.31s) but this is mainly limited by the calculation of the …

Optimize lookup_axis1

---

flamedisx/source.py

If the likelihood sets a new default via params, it currently isn't passed through tf.constant

Always pass defaults through tf.constant

---

flamedisx/er_nr_base.py
requirements.txt
tests/test_source.py

_This PR needs to merged **after** PR #24. I'll probably rebase this branch to get the commit history cleaned before merging._
This adds the option for `LXeSource` sources to have a 3D spatial response (i.e. the rate of events depends also on the interaction position of the event in the TPC).
This can be used to model for example ER events from materials background which are located primarily at the edges of the detector. Using the observed position of events from sources with different spatial responses improves discrimination power. In combination with PR #24 this allows flamedisx to use full 6D (S1, S2, x, y, z, t) sources and likelihood.
Caveats:
- The spatial response histogram simply multiplies the differential rate at a given position. This means that correlations between the …

Add spatial response to sources

---

flamedisx/er_nr_base.py
flamedisx/utils.py
tests/test_source.py

_This builds on #24 and #27 which need to be merged first (after which this branch might need to be rebased on master)_
This rewrites `random_truth` of `LXeSource` to solve issue #23.
When simulating events, random true values are drawn using `random_truth`. It was possible to fix the position of events by passing an event (in the form of a one-row pandas DataFrame) with `fix_truth`. This PR makes `fix_truth` also accept a dictionary whose keys can be any event observable and whose values are used for the simulated events instead of random values. This allows us to fix either the position, time or energy (or a combination thereof) when simulating events.
As a side effect of this more general implementation the `WIMPSource` now also works with an optional spatial response histogram. …

Fixing observables in simulate

---

flamedisx/er_nr_base.py
tests/test_source.py

This fixes a bug introduced in PR #30 where `self.es` had been removed in too many places. This bug was not caught by our tests since `WIMPSource` is not tested against.
* I've added a quick fix which solves the immediate problem. But we should rewrite the `WIMPSource.__init__` since it's not so well designed at the moment. I've opened issue #32  for this.
* I've added `WIMPSource` to the pytest fixture in `test_source.py` so that it also runs our source tests.

WIMPSource bugfix and test

---

flamedisx/inference.py
flamedisx/source.py
flamedisx/x1t_sr1.py

In this pull request a few key features were fixed and updated:
- In the x1t_sr1.py the SR1Source was updated to take random_truth, which makes ERSource usable again
- The NRSource was added and takes also the extra needed columns of 'x_observed' and 'y_observed' from the correction maps #29 
- The use of ColumnSource was checked and a few bugs were fixed:
- defaults were added to the initialisation of the source
- the source can be initialised with data = None
- an important bug was fixed in the shape of data given to the source, where the number of batches was given instead of the batch size #33 
Work to be done: 
Update the NRSource model to fit the AmBe data better and possibly update the defaults of it.

Update sr1 ER and NRSource, fix bugs and usage of ColumnSource

---

flamedisx/source.py

Windows likes this. And it's probably not necessary either, the function just returns a single value from the data tensor -- this is not performance-limiting given all the other stuff we're doing.

Do not trace columnsource's differential_rate

---

flamedisx/er_nr_base.py
flamedisx/utils.py

To solve issue #37, this PR changes the computation of the beta binomial pmf. Instead of computing the probability of observing a number of electrons given `p_electron` we compute the probability of observing a number of photons given `1 - p_electron` (`p_electron_fluctuation` remaining the same).
This prevents large `p_electron` values being used resulting in numerical errors.
We could consider removing or relaxing the `MAX_MEAN_P` and `MIN_FLUCTUATION_P` bounds. I've reverted `safe_p`, but kept the check inside `beta_binom_pmf` since there it checks `1 - p_mean` but it might be better to rename it.
`MIN_FLUCTUATION_P` we could keep for the moment.

Compute beta-binomial pmf on photons instead of electrons

---

flamedisx/inference.py
flamedisx/source.py
tests/test_inference.py

This PR implements construction of likelihoods without data to solve issue #26.
`LogLikelihood` can now be initialized with `data=None`, then call `set_data(data)` on your likelihood later to set dataset `data`. Take care to choose an appropriate `batch_size` in case you are dealing with small datasets (the number of events needs to be at least half the batch size for the padding to work). When passing very small datasets to the initializer (of either Source or LogLikelihood) `batch_size` is adjusted but this is of course not possible when `data=None`. I've added an assert for this in the `Source._init_padding` and tests for constructing single and multiple source likelihoods without data.

Construct Likelihood without data

---

flamedisx/inference.py
tests/test_inference.py

This adds a simulate method to `LogLikelihood`, solving issue #16.
Simulate computes the mean number of events to simulate from each source in the likelihood by multiplying `mu(params)` with the rate multiplier. The rate multiplier can be specified in the `rate_multipliers` dict, otherwise the rate is determined via `_get_rate_mult`.
Optionally `fix_truth` is passed to the source simulator as well.
After simulating events from each source the DataFrames are concatenated and shuffled.
@JelleAalbers Do we need to add livetime as well? I saw that this is how its done in blueice but it's simply another multiplier on mu so can be put in the rate multiplier as well, any thoughts?

Likelihood simulate

---

flamedisx/inference.py
flamedisx/x1t_sr1.py
notebooks/Tutorial.ipynb
requirements.txt
tests/test_inference.py

In this pull request I have added the Minuit optimiser and updated the NRSource for SR1.
Further more as discussed in issue #36 I have taken out the scaling of the parameters in the optimiser since it seemed to give problems with the error computation. 
The Minuit optimiser needs some polishing but from testing seems to work very well and the computation time penalty doesn't seem to be too great (roughly a factor 2) with respect to the tensorflow optimiser. 
The main advantage of Minuit comes from the fact that bounds can be given to the parameters and this avoids the useless stepping into negative parameter values and nan-s from the objective function. 
Possible improvements to this implementation are: 
- give automatic bounds to the parameters and not leave them as keyword arguments
- …

Add Minuit optimiser and update NRSource

---

flamedisx/inference.py
flamedisx/source.py

Don't call the simulator when simulating zero events (when setting for example the rate multiplier to 0)
Removed some redundant whitespace and fixed an assert message.

Don't simulate zero events

---

flamedisx/inference.py
notebooks/Tutorial.ipynb
tests/test_inference.py

This:
* Changes the default optimizer back to bfgs. For running the tutorial on a CPU, this means the fits complete in 5-10 seconds rather than a minute.
* Add a default stepsize of 0.1 * the guess to the minuit parameters. If we don't do this we get a warning and it will use 1 as the stepsize, at least for the rate multiplier (for which this is very large)
* Make bestfit just return the bestfit dictionary without errors as default, so we don't need to do [0] every time. You can get the error dict by passing return_errors=True if you are using minuit. Alternatively we can look into returning some kind of FitResult namedtuple, with .errors and .result as attributes.
* Adds explicit colab instructions to the tutorial.

Revert default to bfgs, add minuit stepsize

---

flamedisx/inference.py
flamedisx/source.py
flamedisx/x1t_sr1.py

As stated in issue #50 I have come across a problem when trying to use different sources in the likelihood. If the different sources use different parameters the likelihood initialisation would fail since it was designed to use the same sets of parameters for all the sources. 
With this pull request I have changed the way we filter the parameters and appropriately give them to the sources they are used in.
To do so I had to initialise the sources with `data = None` a first time, read the defaults and compare the defaults with the parameters given. If the parameters given are in the defaults of one source they are given to a second final initialisation of the source they are used in, this time with the data as well. 
This is probably not the most elegant way to do it, but it works and it …

Different parameters to different sources in the initialisation of the likelihood

---

flamedisx/likelihood.py
flamedisx/source.py
tests/test_likelihood.py

~~_Needs to be merged after #54 , might need a rebase_~~ Done, rebased onto master
This implements retracing of the loglikelihood function (and loglikelihood_grad2) whenever `LogLikelihood.set_data` is called, solving issue #53 
A test has been added to test exactly this issue.
Ideally we would rewrite loglikelihood to accept a `datatensor` and `ptensor` just like the `differential_rate`. Unfortunately we can't write an input signature at the moment since they can't take kwargs.
Edit:
I've added a commit which makes tracing of the likelihood via `set_data` optional (by adding the `autograph` flag to `set_data`). Also when initializing `LogLikelihood` tracing will only be done if data is supplied. This ensures we don't waste time by tracing if we're only calling `log_likelihood` with …

Issue 53 retrace

---

flamedisx/likelihood.py
flamedisx/source.py

The `LogLikelihood.simulate` was applying the efficiencies twice (first when determining the mean expected events and then again in `Source.simulate`) leading to underestimated rate multipliers.
Calling `mu_before_efficiencies` in the likelihood and letting `Source.simulate` deal with the efficiencies fixes this.
Calling `mu_before_efficiencies` means all sources must have this method implemented, the abstract method has been moved up to `SourceBase`. `ColumnSource.mu_before_efficiencies` simply returns it's `mu` since it's a fixed rate source.

Simulator fix

---

.travis.yml
flamedisx/er_nr_base.py
flamedisx/likelihood.py
flamedisx/source.py
flamedisx/utils.py
flamedisx/x1t_sr0.py
flamedisx/x1t_sr1.py
requirements.txt
setup.py
tests/test_inference.py
tests/test_likelihood.py
tests/test_utils.py

Larger changes and improvements:
- Ensure that `Source.differential_rate` only needs to be traced once during the lifetime of a Source object.
- Tracing is now defined in the source initialization since the input signature is known.
- We use `tf.function` to graph the diff rate function and supply an input signature for it. This means that if only the values (and not the shape and dtype) of `data_tensor` and `ptensor` change we don't need to retrace. However we were actually retracing on every `set_data` call which is now fixed. This means that we also had to merge `energy_tensor` and `spatial_rate_tensor` into `data_tensor` so that all is passed through `_differential_rate`.
- Remove all tracing in `log_likelihood`
- Most of the performance gain from using `tf.function` is due to …

Simulator checks and timestamps

---

flamedisx/inference.py
flamedisx/likelihood.py
flamedisx/source.py
flamedisx/utils.py
tests/test_inference.py
tests/test_mock_inference.py
tests/test_source.py

Objective tilt
------------------
Our limit/interval search currently stops when the -2 log likelihood reaches a critical value (set by the confidence level). If there are nuisance parameters, this can be anywhere along an asymptotically elliptical likelihood contour. (Which is not good.)
The actual solution is at the extreme values of the target parameter on this contour -- since the confidence interval encloses the full contour. We can ensure we get to the extreme value of the likelihood contour by adding a tilt term to the objective:
objective = (f(x) - f_0)^2 - w * (x - xhat) / sigma
Here:
* f(x) is the -2 log likelihood difference from the global-bestfit likelihood. This depends on both x and any nuisance parameters.
* f_0 the desired critical value (e.g. 1.64 to get an asymptotic …

Tilt to objective, inference refactor

---

flamedisx/inference.py
flamedisx/likelihood.py
flamedisx/source.py
tests/test_inference.py
tests/test_likelihood.py
tests/test_mock_inference.py

This:
* Enables autograph mode for the `_log_likelihood` function, which computes the likelihood of a single batch and dataset (for all sources in that dataset).
* Avoids using tensorflow in higher-level functions, i.e. convert to numpy immediately after `_log_likelihood`.
* Removes the test for the tensorflow-probability minimizer. 
The main reason for this change is performance: eager tensorflow has a much higher per-computation overhead  than autograph tensorflow or numpy, but the computations after _log_likelihood are all small and on tiny bits of data -- both the sum over events and that over sources have already happened at that point.
For simple likelihoods made of ColumnSources, i.e. where the likelihood per event is precomputed, the eager-mode computation made up the vast …

Trace log likelihood, then no more tensorflow

---

flamedisx/er_nr_base.py
flamedisx/source.py
flamedisx/x1t_sr0.py

This implements a cut on cS1 for SR0 sources to remove an artifact seen when comparing the differential rate of a template based cS1, cS2 method compared to flamedisx.
This is necessary because at very low cS1 the number of detected events drops very steeply and the finite binning of the template doesn't accurately reproduce the differential rate at these energies.
We cannot place a hard cut on cS1 since it will remove events and give an incorrect normalization of the differential rate. However since cS1 is a function of S1, photon gain and photon detection efficiency we can combine it with the s1 acceptance calculation, this is done in `x1t_sr0.py`.
Secondly we no longer need `s1_acceptance` and `s2_acceptance` to be `special_data_methods` since we can put `s1` and `s2` in the data …

cS1 cut and special_data_method cleanup

---

flamedisx/er_nr_base.py
tests/test_source.py

This changes the specification of the TPC dimensions in `LXeSource` to use a simple cylindrical fiducial volume instead. By default the behaviour is the same since the whole TPC is set a FV. Using `fv_radius` the maximum radius of events is set. `fv_high` and `fv_low` set the maximum and minimum depth respectively.
Setting the old `tpc_radius` and `tpc_length` parameters now raises a `DeprecationWarning`
An unnecessary reshape in `add_extra_columns` has been removed.
S1,S2 placeholder values have been removed from `random_truth_observables`, they are no longer needed for `set_data` to work. This was originally needed for bounds computation.
Lastly when drawing `event_time` values (which are O(10^18) integers) don't convert them to floats to preserve precision (they will eventually end up …

FV specification

---

flamedisx/er_nr_base.py
flamedisx/source.py

This improves the simulator speed by a factor ~2:
* Do not call annotate when restoring old data in set_temporarily
* Remove redundant ppf(cdf(x)) to just x calls in the bound estimation -- since ppf(cdf(x)) is just the identity.
* Remove unnecessary use of tensorflow's `clip_by_value` inside annotate. Since we're in numpy/pandas land, `np.clip` is faster.

Simulator optimizations

---

flamedisx/er_nr_base.py
flamedisx/likelihood.py
flamedisx/source.py
tests/test_likelihood.py
tests/test_source.py

This lets flamedisx check that the likelihood has a finite value at the guess, and checks the inferred S1 and S2 acceptances and detection efficiencies are positive for all events. A common case where the latter would fail is if you forget to apply cuts you told flamedisx about.
Curiously, the trust-constr optimizer throws some ValueError about dimension mismatch for the Hessian in case the guess's likelihood is nonfinite. Not sure what this is about, but I hope we won't see this is again with this check.
I introduced a new `_check_data` function in source, since the check on the S1 acceptance cannot happen directly in annotate (for simulated data, annotate is first called without S1 and S2 values defined ), and so we can also check all required columns are present in the data before …

Add sanity checks on the input data and guess

---

.travis.yml
tests/test_utils.py

With the release of Tensorflow 2.2.0 our build now also runs on Python 3.8. I suggest we test Py36 and Py38 instead of Py36 and Py37.

Python 3.8 builds

---

flamedisx/inference.py
tests/test_inference.py

This PR addresses part of issue https://github.com/FlamTeam/flamedisx-notebooks/issues/2
This re-implements the normalization of parameters used by the different optimizers. We had implemented this before but removed it in #40 following a discussion in #36 without really understanding the root cause and assuming that the optimizers work well also with unnormalized/physical parameters. Using SciPy's `trust-constr` method (the current default, because it takes bounds and the hessian) we see in the [Tutorial notebook](https://github.com/FlamTeam/flamedisx-notebooks/blob/master/Tutorial.ipynb) that it has a problem when parameters have values which differ by orders of magnitudes (elife and rate_multiplier). See issue https://github.com/FlamTeam/flamedisx-notebooks/issues/2
Using normalized …

Dimension scaling inside optimizers

---

flamedisx/likelihood.py

For sources with free rates, we currently use a rate multiplier guess of 1. In the common case of one free source, we can easily guess much better based on the number of observed events.
This modifies `Likelihood.set_data` to adjust the default rate multiplier for the first free source in every dataset to `(n_observed - mu_other_sources) / mu_source`. This means we shouldn't have to guess the `er_rate_multiplier` anymore in e.g. the tutorial.
I also extended the `Likelihood.mu` function so you can ask e.g. `ll.mu(source='er')` to get the expected number of ER events. (At the moment you still get a tensorflow constant back though, reflecting its internal use.)

Auto-guess rate multipliers

---

flamedisx/x1t_sr1.py

This fixes #75 where events with zero S2 acceptance are sometimes simulated.
This was due to `s2_acceptance` being redefined only in the SR1 ER source but not in the SR1 NR source causing ER events with S2s down to 100 pe (correctly) being simulated but then wrongly rejected later by the NR model which still used the default 200 pe threshold.
This moves the acceptance function to the `SR1Source` class such that both ER and NR sources use consistent acceptances.
I've checked that the error does not reappear using the code snippet linked in #75, since the original problem was non-deterministic I've also ran the test with 100 different random seeds, none of which now fail.

Bugfix issue 75

---

flamedisx/er_nr_base.py
tests/test_source.py

This implements double photoelectron emission (dpe) modeling using a binomial process instead of the previous gaussian approximation making the model more realistic for low energy S1s.
The probability of the number of dpe's is modeled as: `n_pe - n_photons ~ Binom(n_photons, p=p_dpe)` where `n_pe` is the number of photoelectrons detected, `n_photons` is the number of photons detected and `p_dpe` is de dpe fraction.
To implement this an extra tensor of shape `(n_events, n_photoelectron detected, n_photon detected)` is added to the core flamedisx model and an extra inner dimension `photoelectron_detected` is added. Bounds estimation and simulation is added as well.
The changes have been validated using the [models_check notebook](https://github.com/FlamTeam/flamedisx-notebooks/blob/master/mo …

Double photoelectron emission modeling

---

flamedisx/inference.py
flamedisx/likelihood.py

* Fix a bug in the guess of the scipy optimizers. After the scaling in #72, the guess is not necessarily an array of ones; depending on the signs of the defaults, a guess can also be 0 or -1. With this fix, I don't see the optimizer asking for out-of-bounds values anymore in the tutorial fits.
* Fix a <= vs < bug that prevented the optimizer from evaluating likelihoods exactly at upper bounds; we just slapped it with NaN if it tried.
* Use the initial parameter specification by the user as default bounds on all variables. E.g.if you specify `elife=(300e3, 500e3, 2)`, elife isn't allowed to go outside [300e3, 500e3] anymore. To turn off this behaviour, you can either pass `bounds_specified=False` to `Likelihood.__init__`, or set the `bounds` dictionary for any particular optimization …

Optimization improvements

---

flamedisx/er_nr_base.py
flamedisx/utils.py
tests/test_likelihood.py

This fixes two issues in flamedisx's beta bimomial:
1. We incorrectly computed the beta distribution's alpha and beta given a mean and sigma;
2. We allowed for bimodal beta distributions, for sufficiently high fluctuations.
I will call alpha = a, beta = b, mean = m, variance = sigma**2 = s for simplicity.
We assumed v = 1/(8 b + 4), but this only holds exactly when a = b. The general expression is v = a b / ((a + b)^2 (a + b + 1)). We can still solve (a, b) given (m, s), though it is [slightly hairier](https://www.wolframalpha.com/input/?i=solve+v+%3D%3D+a+b+%2F+%28%28a+%2B+b%29%5E2+%28a+%2B+b+%2B+1%29%29+and+m+%3D%3D+a%2F%28a%2Bb%29+for+a+and+b).
We did not notice this earlier because  
- Recombination fluctuations are an extremely small effect at low energies, compared to statistical …

Fix beta-binomial bug and bimodality

---

flamedisx/xenon/x1t_sr1.py

This fixes #88 
It adds the cS1,cS2 computation to `add_extra_columns` of  `SR1Source`, in the same way as is done in `SR0Source`. As noted in a comment in the original implementation in `SR0Source`: 'this is a kludge'. Would it be better to add cS1 and cS2 as model functions instead?

Add cS1,cS2 computation to SR1Source

---

flamedisx/lxe_blocks/double_pe.py

The `photons_detected_mle` variable, i.e. the maximum-likelihood estimate of photons detected, was rounded to an integer. While technically correct, this causes information loss, so that other variables (e.g. `photons_produced_mle`, `e_vis_mle`) will appear coarser. It is also inconsistent with `electrons_detected_mle`, which is not rounded.
I noticed this because the final output the tutorial now looks odd:
After this fix, it looks fine again:

Do not round MLE of photons detected

---

docs/source/blocks.rst
docs/source/reference/flamedisx.lxe_blocks.rst
docs/source/reference/flamedisx.rst
docs/source/reference/flamedisx.xenon.rst

This adds documentation about adding extra columns/dimensions to flamedisx models. This hopefully clarifies some puzzling behaviour @plt109 recently encountered.

Add docs on models with extra columns/dimensions

---

flamedisx/lxe_blocks/energy_spectrum.py

In flamedisx, `random_truth` and its minions `draw_positions` and `draw_time` get `**kwargs` of (shape) parameters. This is to help sources whose space , time, or energy distribution depend on fittable parameters. The default sources have no such dependencies, so they simply ignore these extra parameters.
`SpatialRateEnergySpectrum`'s `draw_positions` erroneously didn't accept this `**kwargs`, causing #104. This should fix that.

SpatialRateEnergySpectrum's draw_positions should accept parameters

---

flamedisx/xenon/x1t_sr1.py

These are two small changes to x1t_sr1.py:
* The bias and reconstruction efficiency pivot parameter names are currently `bias_pivot_pt1`, `bias_pivot_pt2` and `scalar`. These names end up in fit results, and have to be specified by the user (e.g. in the Likelihood construction, if you want to fit these parameters). This gives them a bit more descriptive names, `s1_reconstruction_bias_pivot`, `s2_reconstruction_bias_pivot` and `s1_reconstruction_efficiency_pivot`.
* In `cal_rec_efficiency_tf`, an `if pivot_pt < 0` is used. Tensorflow _should_ be able to resolve this (see [here](https://www.tensorflow.org/guide/function#conditionals)), but it could be a problem for certain versions, or perhaps certain orders in which the functions are traced. Sophia ran into a problem with this in #101. …

Name reconstruction efficiency pivots

---

flamedisx/likelihood.py
flamedisx/utils.py

A few small fixes/enhancements to flamedisx.Likelihood:
* A new `defaults` argument for `Likelihood.__init__`. This allows you to override defaults for all sources. Now you can collect all your custom defaults in one place (e.g. a config file), load them into a dictionary, then pass them to your likelihood.
* `Likelihood.guess` should output a dict of python values, not tf.constants. This is consistent with the output of e.g. `Likelihood.bestfit` and other functions.
* If the likelihood had shape parameters, you could not call `.simulate()` without arguments. Now you can; omitted parameters are replaced by their defaults.
* Conversely, if you passed shape parameters the likelihood did not take, those parameters were just ignored. So you might think   `Likelihood.simulate(elife=0)` runs a …

Minor likelihood fixes/enhancements

---

flamedisx/source.py
tests/test_source.py

This fixes a bug in `Source._set_temporarily`. This low-level function is used during simulation and annotation to temporarily set data and parameters to different values. It's supposed to return a source to the previous state afterwards. 
... only it didn't properly reset the parameters. Thus, if you call simulate/annotate with non-default settings, the default settings actually get overwritten!
This can cause serious trouble, e.g. after
```python
import flamedisx as fd
ll = fd.LogLikelihood(
sources=dict(er=fd.ERSource),
elife=(1e6, 1e12, 2))
```
the `ll.sources['er'].defaults['elife']` is now actually 1e12 ns. If you now use e.g. `ll.sources['er'].simulate`, you will be in for a surprise... Fortunately, the likelihood does still remember the original defaults, so you're fine if you use …

Fix 'sticky' defaults

---

flamedisx/lxe_blocks/energy_spectrum.py
tests/test_source.py

This simplifies the API of the spatial rate sources. After this, users only have to specify a `spatial_hist` attribute, containing a regular, un-normalized, events/bin histogram of event positions. Flamedisx will do all normalization and conversions it needs internally.
---------
Currently, users instead have to 
* convert their histograms to an undocumented normalization convention, and
* pass the physical bin_volumes explicitly, even though we can deduce these from the histogram coordinate names and bin edges.
By trial/error/reverse-engineering, it seems we currently require something like this:
* Convert histogram to a PDF (normalize, then divide by physical bin volume)
* Divide by the mean over bins, __without__ weighting by any bin volume
* Multiply by the bin volumes
Maybe there is …

Simplify SpatialRateEnergySpectrum API

---

flamedisx/xenon/data.py
flamedisx/xenon/x1t_sr1.py

This allows the user to read files stored in the XENONnT/Flamedisx private repository after the necessary authentication token has been set up. 
```
fname_1t = '1t_maps/test_map.json'
map_1t = fd.get_nt_file(fname_1t)
fname_nt = 'nt_maps/test_map.json'
map_nt = fd.get_nt_file(fname_nt)
```
As the repository gets updated, the user might be required to update his/her local version of the repository. This can be achieved with
```
fd.refresh_nt()
```
which deletes the current local XENONnT Flamedisx private repo and clones the latest version.

Read data from XENONnT Flamedisx private repo

---

flamedisx/xenon/x1t_sr1.py

Changes only affect the ER model in xenon/x1t_sr1.py
The electron lifetime is interpolated from the electron lifetime map pulled from the XENONnT/Flamedisx private repository based on the event time of the event and added as a column in `add_extra_columns`. Subsequently, also in `add_extra_columns`, the cs2 value is calculated using this interpolated electron lifetime instead of the default value of 641us which was previously hardcoded in.
The electron lifetime information is then used in model function `electron_detection_eff` as a positional argument. It was previously a keyword argument (nuisance parameter) which had a default value of 641us.
Performance of this new model, along with ks p-value distributions from multiple MC toys, is documented in [Convo …

Elife interpolated from elife map from private repo

---

flamedisx/xenon/resource.py

This PR adds the `.npz` file format to the list of formats supported by `get_resource` by adding it to the end of the list at https://github.com/FlamTeam/flamedisx/blob/14a15921668f8501e16b219f3438ad59837c700e/flamedisx/xenon/resource.py#L97
The field distortion simulation maps are currently stored in the `.npz` format and this PR allows the user to load those maps with `get_resource'.
This new functionality has been tested on a local machine and on Fried Rice.

added npz to list of supported formats by get_resource

---

flamedisx/xenon/x1t_sr1.py

Removed `import pdb as pdb` and unused inputs,`r, z`  for `p_electron`.
These lines were missed out during the review of PR #118.

removed pdb and extra unused inputs for p_electron

---

.gitignore
flamedisx/block_source.py
flamedisx/likelihood.py
flamedisx/lxe_blocks/detection.py
flamedisx/lxe_blocks/double_pe.py
flamedisx/lxe_blocks/energy_spectrum.py
flamedisx/lxe_blocks/final_signals.py
flamedisx/lxe_blocks/quanta_generation.py
flamedisx/lxe_blocks/quanta_splitting.py
flamedisx/lxe_sources.py
flamedisx/source.py
flamedisx/utils.py
tests/test_source.py

Summary [here ](https://docs.google.com/presentation/d/1b4xh2-nUhBhnscXNoUEcthufW74W4wGHXgzD52QBe4Q/edit?usp=sharing)
This PR implements variable stepping into Flamedisx, for both the current default models and any future sets of models (i.e. the NEST models which I will port over next).
This was a LOT more work than I had envisaged: this is due to the way that the FD default models relate the energy spectrum to the quanta tensor, and the associated issues that variable stepping caused there. It wasn't an issue present in the NEST version, so I hadn't had to solve it until now. 
The slides should summarise this, the solution, the implementation of the stepping and the various other features I had to implement to get around this problem. I have tried to keep those features very generalised …

Rj variable stepping

---

flamedisx/xenon/itp_map.py
flamedisx/xenon/x1t_sr1.py

Small pull request to fix the SR1 S2 acceptance to account for the S2<200pe necessary for sources that produce low S2s and force the map reading to read floats.

fix s2 acceptance and force float in map reading

---

.gitignore
docs/source/blocks.rst
flamedisx/block_source.py
flamedisx/likelihood.py
flamedisx/lxe_blocks/energy_spectrum.py
flamedisx/source.py
flamedisx/utils.py

This is a documentation update:
* Add comments with `#:` for attributes of `Source`, `BlockSource`, and a few other classes. These will appear in our [API reference](https://flamedisx.readthedocs.io/en/latest/reference/flamedisx.html#module-flamedisx.source) after this is merged.
* Fix some problems with the block system documentation:
* Several subsection headings did not appear;
* The arguments to `_compute ` were never described;
* Model attributes, which are relatively rare, were more prominently documented than model functions and dimensions, which are both used in every block. They were also occasionally referred to as 'static attributes', their old name.
* Fix a few docstrings that weren't compatible with sphinx, and thus looked weird in the API reference.

Documentation update: source attributes, block system, sphinx docstrings

---

flamedisx/xenon/itp_map.py
flamedisx/xenon/x1t_sr1.py

As a follow-up test suggested by @JelleAalbers in https://github.com/FlamTeam/flamedisx/pull/140#issuecomment-864475656, the main changes in this PR occur in `x1t_sr1.py` the paths of the elife, cut efficiency, reconstruction bias mean, etc maps are moved inside `class SR1Source` so that the map paths are configurable as well.
The change in `itp_map.py` insists of specific type casting of the map values so that the new nT maps could be read in as well.
The changes are then tested on a local machine with 
```
class newSource(fd.SR1ERSource):
specificSource = newSource(config=my_config_path)
specificSource.print_config(column_widths=(40, 99))
```
returning the output shown in the screenshot, which displayed the expected values.

Test config

---

flamedisx/lux/lux.py
flamedisx/nest/lxe_blocks/pe_detection.py
flamedisx/nest/lxe_blocks/secondary_quanta_generation.py
flamedisx/nest/lxe_sources.py

Some small bug fixes for the NEST sources:
- Fix syntax in LUX sources after Jelle's changes
- Avoid S1 photoelectron detection binomial returning `nan`
- Temporary fix to `_annotate()` in pe_detection.py: will return to properly fix this later
- Fix where one block was accidentally using TensorFlow for `simulate()`
- No stepping for the sharply peaked S1 photoelectron detection binomial

Various bug fixes for NEST sources.

---

flamedisx/xenon/x1t_sr1.py

This update provides a source for surface events in xenon TPCs. The source is based on an ER source with spatial dependence.
To function the source needs a spatial template to be given. To create the spatial template a utility function is also provided: 
The function `construct_exponential_r_spatial_hist` can be used to construct a 3D multihist to be given to the wall source.
The wall source is constructed from a simplified flat ER band, with a much reduced electron extraction efficiency to account for the charge loss inside the TPC. The parameters of the source were tuned through fitting wall leakage data from XENON1T. 
The source and the fitting describes well enough the wall events and provides an alternative with some physical interpretation. The source can be reduced to have only …

Wall source

---

flamedisx/xenon/x1t_sr1.py

This pull request fixes a bug in `add_extra_columns` and updates the conditions under which `cs1` and `cs2` are computed so that they are only computed for the simulated events and not replaced in actual data.

bug fix in add_extra_columns to only add cs1, cs2 for simulated events

---

flamedisx/inference.py
flamedisx/likelihood.py

This PR fixes a bug in the computation of the covariance matrix used in `LogLikelihood.summary` and the computing a starting guess for the interval computation.
Mathematically, the estimator of the asymptotic covariance matrix is the inverse of the Fisher information matrix evaluated at the bestfit parameters of the fit. See [stack exchange article here](https://stats.stackexchange.com/questions/68080/basic-question-about-fisher-information-matrix-and-relationship-to-hessian-and-s) (or pg 101-102 of Statistical Methods in Experimental Physics 2nd Edition by Fred James).
`LogLikelihood.inverse_hessian` returns the inverse of the hessian of -2 loglikelihood, whereas the covariance is the inverse of the hessian of -loglikelihood.
The implementation of `LogLikelihood.inverse_hessian` is kept …

Fix hessian bug

---

flamedisx/xenon/x1t_sr1.py

The default drift field is made a model attribute so that it can be set via a configuration file instead of changing the value of `DEFAULT_DRIFT_FIELD` in `x1t_sr1.py`. This is useful to adapt the current drift field value which was set to the field value of xenon1T SR1 to the nominal drift field value in xenonnT. Note that the drift field is still a single value throughout the entire TPC (drift field is not a function of position).
The changes in this PR affect both `fd.SR1ERSource` and `fd.SR1NRSource` via `p_electron` in each of these sources. To ensure that the changes do not induce any bugs in the fitting process, MC events were simulated and fitted for both `fd.SR1ERSource` and `fd.SR1NRSource`.
For `fd.SR1ERSource`, the optimizer converged as expected (the biases are still there, …

Add field to config

---

flamedisx/xenon/x1t_sr1.py

[PR 217](https://github.com/FlamTeam/flamedisx/pull/217) has a messy commit history so I created another branch with the same changes but from a repo without a messy commit history, and tested the changes again.
The default s2 area fraction top is made a model attribute, `s2_area_fraction_top`, so that it can be set via a configuration file instead of changing the value of `DEFAULT_AREA_FRACTION_TOP` in `x1t_sr1.py`. It is also explicitly called `s2_area_fraction_top` to differentiate it from `s1_area_fraction_top` which is used in other cuts currently not explicitly used in flamedisx.
This is useful to change the s2 area fraction top value which is used to compute the cs2b values in `s2_acceptance` and apply the cuts on cs2b.
The changes in this PR affect both `fd.SR1ERSource`, …

add s2 aft into model attributes configurable via config files

---

.github/workflows/test_flamedisx.yml
flamedisx/utils.py
flamedisx/xenon/itp_map.py
flamedisx/xenon/x1t_sr1.py

The spatial variation of the drift field gets increasingly important as liquid xenon TPCs become larger. The ability to model such inhomogeneities in the drift field also opens up the possibility of extending the fiducial volume instead of trimming those regions away.
This pull request allows the user to incorporate a spatially dependent drift field into `SR1ERSource` and `SR1NRSource` which is interpolated from an external drift field map. The field distortion and field distortion correction are also included.
The fit to ER MC events converges without any issue even though the bias is still there:
The fit to NR MC events converges without any issue even though the bias is still there:
@Ashley-Joy, you might want to test this to make sure that the changes do not cause any breaking changes …

Add field map

---

flamedisx/lxe_blocks/energy_spectrum.py

This pull request introduces another class variable `exposure_tonneyear` to the `WIMPEnergySpectrum` class so that it is easier to change the exposure of the WIMP source.
The spectra computed by `wimprates.rate_wimp_std` is in the units of events / (keV tonne year) and it is scaled by the exposure in units of tonne year [in this line](https://github.com/FlamTeam/flamedisx/blob/d371b34db4de2256f3697a5e08d02e260ef40787/flamedisx/lxe_blocks/energy_spectrum.py#L358).
The way to scaling the WIMP rate is inspired by @pelssers's [sensitivity studies notebook](https://github.com/FlamTeam/flamedisx-notebooks/blob/b8acfdf8fcc2c191fe1882706466c442e46a92ed/flamedisx_sensitivity.ipynb). He tried to scale the spectrum from the class but there is a comment that suggests that that would not work because …

Exposure in wimp source

---

flamedisx/__init__.py
flamedisx/block_source.py
flamedisx/likelihood.py
flamedisx/lxe_blocks/energy_spectrum.py
flamedisx/mu_estimation.py
flamedisx/source.py
tests/test_likelihood.py
tests/test_mu.py

This expands flamedisx's options for estimating the total expected events ('mu'). It mostly prepares the ground for implementing new mu estimation methods in the near future, rather than adding new methods.
Specifying different mu estimation methods
----------------------------------------------------------
See issue #71. A new `mu_estimators` argument to `Likelihood.__init__` controls how mu estimators are built:
* `fd.CrossInterpolatedMu` (the default) will use the current algorithm.
* `fd.SimulateEachCallMu` does a completely new simulation each call. This does not actually work -- it makes the likelihood non-differentiable. But it could be useful for debugging, or for future developement (I think Pueh is looking into this)
* `fd.ConstantMu` assumes mu is a constant. Perhaps useful to …

Mu estimation options, saving and loading

---

flamedisx/__init__.py
flamedisx/templates.py
tests/test_template.py

This allows users to specify sources using histograms that contain expected events/bin or differential rates. This is useful for sources like accidental coincides that have empirical models, and for cross-checks on the main flamedisx computation. Here's an example:
```python
source = fd.TemplateSource(some_multihist, events_per_bin=True, batch_size=int(1e3))
```
where `some_multihist` is a [multihist](https://github.com/JelleAalbers/multihist) Histdd. You should also be able to pass a [boost-histogram](https://github.com/scikit-hep/boost-histogram) or [hist](https://github.com/scikit-hep/hist) object, though I haven't tested this. Or you can just pass `template`, `bin_edges`, `axis_names` explicitly, setting the former two to numpy arrays and the final one to a sequence of strings. 
For a …

Add simple fixed template source

---

flamedisx/likelihood.py
flamedisx/mu_estimation.py
requirements_minimal.txt
tests/test_mu.py

This PR adds a grid interpolation option. The default number of anchors for a grid interpolated parameter is 3; cross interpolation automatically probes the centre in a roundabout way, but a 2-anchor grid interpolation would not, hence this choice.
As a benchmark, I did a fit with the Xe1T SR1 ER source (@plt109), for g1, gamma_er and omega_er. I used 2 anchors (plus the base mu at the centre) for grid interpolation, and 3 anchors for cross interpolation. Each anchor point had 10^6 simulated events to estimate mu.
The percentage differences between the interpolated and directly estimated mu in each case, at 3 benchmark points, are:
**Cross:**
Bestfit: 7.1%
Lower range for all: 9.4%
Central defaults for all: 4.4%
**Grid:**
Bestfit: 0.13%
Lower range for all: 0.22%
Central defaults for all: …

Rj grid interpolation

---

flamedisx/bounds.py
flamedisx/lux/lux.py
flamedisx/nest/config/default.ini
flamedisx/nest/lxe_blocks/detection.py
flamedisx/nest/lxe_blocks/final_signals.py
flamedisx/nest/lxe_blocks/quanta_splitting.py
flamedisx/nest/lxe_blocks/secondary_quanta_generation.py
flamedisx/nest/lxe_sources.py
flamedisx/nest/parameter_calc.py
flamedisx/utils.py
tests/test_nest.py

Summary/validations [here](https://docs.google.com/presentation/d/1vFyN75oIP0VX1p4PuRGzqJAW8MpAqOrVc8OoeJiXwO8/edit#slide=id.p).

NEST 2.3.0 models update

---

flamedisx/lux/lux.py
flamedisx/nest/lxe_sources.py

This PR adds in the NEST gamma model as well as the weighted beta/gamma model from NEST that has been shown well to fit to certain electron capture decays.
Validations attached below:

Rj new er models

---

flamedisx/block_source.py
flamedisx/source.py

This implements a fix to a bug that's only just come to light. `max_dim_sizes` was, before, a class attribute in `Source`. Blocks in a `BlockSource` could define a `max_dim_size` for their domains, which would then update the `max_dim_sizes` dictionary in the `Source`. The problem comes when you have 2 different types of `BlockSource` that contain blocks which set the `max_dim_size` for the same domain differently. Because `max_dim_sizes` is a class attribute of `Source`, which both `BlockSource`s inherit from, the second source will change the `max_dim_sizes` dictionary for the first source!
This fix makes it an instance attribute instead.

Fix max_dim_sizes bug

---

flamedisx/block_source.py
flamedisx/source.py

This PR enables support for dimensions which are non-integer: this will be especially useful for @plt109's (and later our) reconstruction bias.
Using it is simple: I made a toy example where the final dimension becomes `s1_smear`, giving a Gaussian smearing `s1_smear ~ Normal(s1, 0.01)`. Once this new block has been implemented, and the correct new final dimensions have been flagged up (as before), the only additional change needed is to add
`non_integer_dimensions = ('s1')`
in the source class.
I've attached a validation plot for this model (using a LUX ER source at 10 keV with this new S1 smearing block bolted on, and a `max_dim_size` of 200 for `s1`). I attach that below

Allow for non-integer dimensions.

---

flamedisx/mu_estimation.py

Our builds are currently failing because we missed a trailing whitespace in https://github.com/FlamTeam/flamedisx/pull/285. This removes it.

Fix whitespace for flake8

---

flamedisx/source.py

This old syntax was deprecated in the latest NumPy release

Update after latest numpy release.

---

flamedisx/block_source.py
flamedisx/nest/lxe_sources.py
flamedisx/source.py

**What**: Move all code related to integration and summation (min/max computations, domain stepping, the various `_dimensions` attributions) into a new class named `IntegratingSource`.
**Why**:
* Readability, this collects related code from many places into one place. 
* Simplifies our base Source class; `ColumnSource`s, template sources, etc. do not need all of this mechanics.
* If we want alternatives to our `BlockModelSource` (maybe auto-generating models from equations..) we can now inherit from `IntegratingSource` and keep just the parts we need.
**Related changes**
* Removed the concept of "additional_bounds_dimensions"; all that did was include `{dimension}_min` and `{dimension}_max` in the columns to keep on the tensorflow side. This was also only used in one place, in the NEST …

Refactor bounds/dimension stuff into IntegratingSource

---

flamedisx/templates.py
tests/test_template.py

This adds to the intra-bin interpolation support for template sources that @robertsjames added in #269:
* Support template dimensions other than 2. The `interp_2d` argument is renamed to `interpolate`.
* Avoid the deprecated interp2d function.
* Work correctly if the user specifies an events-per-bin template (instead of the default differential rate template).
* Use linear interpolation instead of a higher-order bivariate spline (which interp2d defaulted to).
* Add a unit test.
Happy to add an argument to change the interpolation method as well, though I'm not sure what higher-order interpolation would do on noisy histogram templates.

Template interpolation 

---

flamedisx/source.py
flamedisx/templates.py
tests/test_template.py

This extends flamedisx's support for "old-fashioned" template sources, by adding support for linear / vertical template morphing. The new `MultiTemplateSource` takes multiple (param dict, histogram) combinations. For example:
```python
source = fd.MultiTemplateSource(
(dict(elife=800, drift_field=120), histogram_1),
(dict(elife=920, drift_field=150), histogram_2),
...)
```
would produce a source that has `elife` and `drift_field` as free parameters, which control a linear interpolation between the differential rate histograms corresponding to those parameters.
Using a rectilinear grid of parameter points is recommended. Something like a cross of points should also work, but internally we interpolate onto a grid anyway on initialization (because tensorflow(_probability) only has …

Template morphing
